apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: charts
  annotations:
    github.com/project-slug: 'backstage/charts'
spec:
  type: service
  lifecycle: production
  owner: backstage/techdocs-maintainers
