{{- if .Values.backstage.appConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-app-config
  namespace: {{ .Release.Namespace | quote }}
data:
  app-config.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.backstage.appConfig "context" $) | nindent 4 }}
{{- end }}
