{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backstage.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    {{- with .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.labels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | trim | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
